CREATE TABLE Email (
	MailID INT PRIMARY KEY IDENTITY(1,1),
	SenderID INT NOT NULL FOREIGN KEY REFERENCES Account(AccountID),
	Subject NVARCHAR(255) NOT NULL,
	Body NVARCHAR(MAX) NOT NULL,
	DateCreated DATETIME NOT NULL
);