CREATE TABLE Account (
	AccountID INT PRIMARY KEY IDENTITY(1,1),
	EmailAddress NVARCHAR(255) NOT NULL UNIQUE,
	AccountName NVARCHAR(255) NOT NULL,
	PasswordHash VARCHAR(255) NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateLastLogin DATETIME NOT NULL
);